# ==========================================================
# NOTEBOOK 2
# CASE REPRESENTATION
# Sistem Case Based Reasoning (CBR)
# ==========================================================

In [1]:
import re
import pandas as pd
from pathlib import Path
from tqdm import tqdm

In [13]:
BASE_DIR = Path.cwd().parent

RAW_DIR = BASE_DIR / "data" / "raw"
PROCESSED_DIR = BASE_DIR / "data" / "processed"

PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

txt_files = sorted(RAW_DIR.glob("*.txt"))

print("Jumlah TXT :",len(txt_files))

Jumlah TXT : 30

In [15]:
def extract_court(text):

    match = re.search(

        r"Pengadilan\s+Negeri\s+([A-Za-z ]+)",

        text,

        re.IGNORECASE

    )

    if match:

        return "Pengadilan Negeri " + match.group(1).strip()

    return "-"

In [16]:
def extract_year(text):

    match = re.search(

        r"/(\d{4})/",

        text

    )

    if match:

        return match.group(1)

    return "-"

In [17]:
def extract_defendant(text):

    patterns = [

        r"Nama lengkap\s*:\s*(.+)",

        r"Nama\s*:\s*(.+)",

        r"Terdakwa\s*:\s*(.+)"

    ]

    for pattern in patterns:

        match = re.search(pattern,text,re.IGNORECASE)

        if match:

            return match.group(1).strip()

    return "-"

In [18]:
def extract_article(text):

    matches = re.findall(

        r"Pasal\s+[0-9A-Za-z\s,().]+",

        text,

        re.IGNORECASE

    )

    if matches:

        return "; ".join(matches)

    return "-"

In [19]:
def extract_verdict(text):

    text_upper = text.upper()

    keywords = [

        "MENGADILI",

        "MENETAPKAN",

        "MEMUTUSKAN"

    ]

    for key in keywords:

        if key in text_upper:

            idx = text_upper.find(key)

            return text[idx:idx+3000]

    return "-"

In [20]:
records = []

for txt_file in tqdm(txt_files):

    with open(txt_file,encoding="utf-8") as f:

        text = f.read()

    records.append({

        "case_id":txt_file.stem,

        "nomor_putusan":extract_case_number(text),

        "pengadilan":extract_court(text),

        "tahun":extract_year(text),

        "nama_terdakwa":extract_defendant(text),

        "pasal":extract_article(text),

        "amar_putusan":extract_verdict(text),

        "isi_putusan":text

    })

df = pd.DataFrame(records)

df.head()

100%|██████████| 30/30 [00:00<00:00, 2289.09it/s]

,case_id,nomor_putusan,pengadilan,tahun,nama_terdakwa,pasal,amar_putusan,isi_putusan
0,case_001,166/Pid.B/2019/PN,Pengadilan Negeri Cibinong yang mengadili perk...,2019,Randy Alias Boy Bin Odih 2. Tempat lahir : Bog...,-,mengadili perkara pidana doengan u acara pemer...,a i s e n o d n I k i l b u p e a R i s g e n ...
1,case_002,182/Pid.B/2021/PN,Pengadilan Negeri Cibinong yang mengadili perk...,2021,Odih Al. Belong Bin Rohaca h k 2. Tempat lahir...,-,mengadili perkara pidana dengan d agcara pemer...,a i s e n o d n I k i l b u p e a R i s g e n ...
2,case_003,182/Pid.B/2021/PN,Pengadilan Negeri Cibinong yang mengadili perk...,2021,Odih Al. Belong Bin Rohaca h k 2. Tempat lahir...,-,mengadili perkara pidana dengan d agcara pemer...,a i s e n o d n I k i l b u p e a R i s g e n ...
3,case_004,tanggal,Pengadilan Negeri Cibinong yang memeriksa dan ...,2020,Inen Bin Boin.Alm; a Tempat lahir : Bogor; i l...,-,mengadili perkara-perkara n Apidana pada perad...,a i s e n o d n I k i l b u p e a R i s g e n ...
4,case_005,190/Pid.B/2023/PN,Pengadilan Negeri Cibinong yang mengadili perk...,2023,Lusky Alias Ulus; 2. Tempat lahir : Karawang; ...,-,mengadili perkara pidana doengan u acara pemer...,a i s e n o d n I k i l b u p e a R i s g e n ...

In [21]:
output = PROCESSED_DIR / "cases.csv"

df.to_csv(output,index=False)

print(output)

c:\Users\Amanda RW\.vscode\CBR_Pidana_Penadahan\data\processed\cases.csv

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   case_id        30 non-null     object
 1   nomor_putusan  30 non-null     object
 2   pengadilan     30 non-null     object
 3   tahun          30 non-null     object
 4   nama_terdakwa  30 non-null     object
 5   pasal          30 non-null     object
 6   amar_putusan   30 non-null     object
 7   isi_putusan    30 non-null     object
dtypes: object(8)
memory usage: 2.0+ KB

In [23]:
df.head()

,case_id,nomor_putusan,pengadilan,tahun,nama_terdakwa,pasal,amar_putusan,isi_putusan
0,case_001,166/Pid.B/2019/PN,Pengadilan Negeri Cibinong yang mengadili perk...,2019,Randy Alias Boy Bin Odih 2. Tempat lahir : Bog...,-,mengadili perkara pidana doengan u acara pemer...,a i s e n o d n I k i l b u p e a R i s g e n ...
1,case_002,182/Pid.B/2021/PN,Pengadilan Negeri Cibinong yang mengadili perk...,2021,Odih Al. Belong Bin Rohaca h k 2. Tempat lahir...,-,mengadili perkara pidana dengan d agcara pemer...,a i s e n o d n I k i l b u p e a R i s g e n ...
2,case_003,182/Pid.B/2021/PN,Pengadilan Negeri Cibinong yang mengadili perk...,2021,Odih Al. Belong Bin Rohaca h k 2. Tempat lahir...,-,mengadili perkara pidana dengan d agcara pemer...,a i s e n o d n I k i l b u p e a R i s g e n ...
3,case_004,tanggal,Pengadilan Negeri Cibinong yang memeriksa dan ...,2020,Inen Bin Boin.Alm; a Tempat lahir : Bogor; i l...,-,mengadili perkara-perkara n Apidana pada perad...,a i s e n o d n I k i l b u p e a R i s g e n ...
4,case_005,190/Pid.B/2023/PN,Pengadilan Negeri Cibinong yang mengadili perk...,2023,Lusky Alias Ulus; 2. Tempat lahir : Karawang; ...,-,mengadili perkara pidana doengan u acara pemer...,a i s e n o d n I k i l b u p e a R i s g e n ...

In [24]:
print("="*80)

print(df.iloc[0]["nomor_putusan"])

print(df.iloc[0]["pengadilan"])

print(df.iloc[0]["tahun"])

print(df.iloc[0]["nama_terdakwa"])

print(df.iloc[0]["pasal"])

print("="*80)

================================================================================
166/Pid.B/2019/PN
Pengadilan Negeri Cibinong yang mengadili perkara pidana doengan u acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai d g berikut dalam perkara Terdakwa
2019
Randy Alias Boy Bin Odih 2. Tempat lahir : Bogor I h3. Umur/Tanggal lahir : 32/26 Oktober 1986 k a 4. Jenis kelamin : Laki-laki i l 5. Kebangsaan : Indonesia m b 6. Tempat tinggal : Kp. Nangoh Rt.002/001 Desa Lemah Duhur Kec. u a Caringin Kab. Bogor 7. Agama : Islam p k 8. Pekerjaan : Tideak Bekerja h a R a i Terdakwa Randy Alias Boy Bin Odih ditahan dalam tahanan rutan oleh: s M 1. Penyidik sejak tanggal 17 Januari 2019 sampai dengan tanggal 5 Februari g e 2019 n n 2. Penyidik Perpanjangan Oleh Penuntut Umum sejak tanggal 6 Februari 2019 o u sampai dengan tanggal 17 Maret 2019 3. Pgenuntut Umum sejak tanggal 18 Maret 2019 sampai dengan tanggdal 6 April 2019 n A 4. Hakim Pengadilan Negeri sejak tanggal 26 Maret 2019 sampai dengan I tanggal 24 April 2019 h k 5. Hakim Pengadilan Negeri Perpanjangan Pertama Oleh Ketua Pengadilan a i Negeri sejak tanggal 25 April 2019 sampai dengan tanggal 23 Juni 2019 l m b Terdakwa menghadap sendiri; u a Pengadilan Negeri tersebut; p k Setelah membaca: e h a - Penetapan Ketua Pengadilan Negeri Cibinong Nomor R a 166/Pid.B/2019/PN Cbi tanggal 26 Maret 2019 tentang penunjukan Majelis i s M Hakim; g e - Penetapan Majelis Hakim Nomor 166/Pid.B/2019/PN Cbi tanggal 26 n Maret 2019 tenntang penetapan hari sidang; - Berkas perkara dan surat-surat lain yang bersangkutan; o u   dari 17 Putusan Nomor 166/Pid.B/2019/PN Cbi d g Form-01/SOP/15.5/2019/PN Cbi n A I h k
-
================================================================================