In [1]:
import os
import pandas as pd

In [2]:
PROJECT_DIR = os.path.abspath("..")

RESULT_PATH = os.path.join(
    PROJECT_DIR,
    "data",
    "results",
    "retrieval_results.csv"
)

retrieval = pd.read_csv(RESULT_PATH)

retrieval

,case_id,nomor_putusan,nama_terdakwa,pasal,amar_putusan,similarity
0,case_001,166/Pid.B/2019/PN,Randy Alias Boy Bin Odih 2. Tempat lahir : Bog...,-,mengadili perkara pidana doengan u acara pemer...,0.955703
1,case_007,241/Pid.B/2019/PN,Nano Bin Patma; I Tempat lahir : Bogor; h k Um...,-,mengadili perkara pidana doengan u acara pemer...,0.554023
2,case_030,99/Pid.B/2019/PN,ISAK Bin IDING n A Tempat lahir : Sukabumi I U...,pasal 480 KRe,mengadili perkara pidana dengan o u acara peme...,0.214651
3,case_002,182/Pid.B/2021/PN,Odih Al. Belong Bin Rohaca h k 2. Tempat lahir...,-,mengadili perkara pidana dengan d agcara pemer...,0.201285
4,case_003,182/Pid.B/2021/PN,Odih Al. Belong Bin Rohaca h k 2. Tempat lahir...,-,mengadili perkara pidana dengan d agcara pemer...,0.201285

In [3]:
DATA_PATH = os.path.join(
    PROJECT_DIR,
    "data",
    "processed",
    "cases.csv"
)

cases = pd.read_csv(DATA_PATH)

cases.head()

,case_id,nomor_putusan,pengadilan,tahun,nama_terdakwa,pasal,amar_putusan,isi_putusan
0,case_001,166/Pid.B/2019/PN,Pengadilan Negeri Cibinong yang mengadili perk...,2019,Randy Alias Boy Bin Odih 2. Tempat lahir : Bog...,-,mengadili perkara pidana doengan u acara pemer...,a i s e n o d n I k i l b u p e a R i s g e n ...
1,case_002,182/Pid.B/2021/PN,Pengadilan Negeri Cibinong yang mengadili perk...,2021,Odih Al. Belong Bin Rohaca h k 2. Tempat lahir...,-,mengadili perkara pidana dengan d agcara pemer...,a i s e n o d n I k i l b u p e a R i s g e n ...
2,case_003,182/Pid.B/2021/PN,Pengadilan Negeri Cibinong yang mengadili perk...,2021,Odih Al. Belong Bin Rohaca h k 2. Tempat lahir...,-,mengadili perkara pidana dengan d agcara pemer...,a i s e n o d n I k i l b u p e a R i s g e n ...
3,case_004,tanggal,Pengadilan Negeri Cibinong yang memeriksa dan ...,2020,Inen Bin Boin.Alm; a Tempat lahir : Bogor; i l...,-,mengadili perkara-perkara n Apidana pada perad...,a i s e n o d n I k i l b u p e a R i s g e n ...
4,case_005,190/Pid.B/2023/PN,Pengadilan Negeri Cibinong yang mengadili perk...,2023,Lusky Alias Ulus; 2. Tempat lahir : Karawang; ...,-,mengadili perkara pidana doengan u acara pemer...,a i s e n o d n I k i l b u p e a R i s g e n ...

In [4]:
best_case = retrieval.iloc[0]

best_case

case_id                                                   case_001
nomor_putusan                                    166/Pid.B/2019/PN
nama_terdakwa    Randy Alias Boy Bin Odih 2. Tempat lahir : Bog...
pasal                                                            -
amar_putusan     mengadili perkara pidana doengan u acara pemer...
similarity                                                0.955703
Name: 0, dtype: object

In [5]:
solution = cases[
    cases["case_id"] == best_case["case_id"]
]

solution

,case_id,nomor_putusan,pengadilan,tahun,nama_terdakwa,pasal,amar_putusan,isi_putusan
0,case_001,166/Pid.B/2019/PN,Pengadilan Negeri Cibinong yang mengadili perk...,2019,Randy Alias Boy Bin Odih 2. Tempat lahir : Bog...,-,mengadili perkara pidana doengan u acara pemer...,a i s e n o d n I k i l b u p e a R i s g e n ...

In [6]:
print("="*60)
print("HASIL REUSE SOLUTION")
print("="*60)

print("Case ID :", solution.iloc[0]["case_id"])
print("Nomor Putusan :", solution.iloc[0]["nomor_putusan"])
print("Nama Terdakwa :", solution.iloc[0]["nama_terdakwa"])
print("Pasal :", solution.iloc[0]["pasal"])
print("Amar Putusan :")
print(solution.iloc[0]["amar_putusan"])

============================================================
HASIL REUSE SOLUTION
============================================================
Case ID : case_001
Nomor Putusan : 166/Pid.B/2019/PN
Nama Terdakwa : Randy Alias Boy Bin Odih 2. Tempat lahir : Bogor I h3. Umur/Tanggal lahir : 32/26 Oktober 1986 k a 4. Jenis kelamin : Laki-laki i l 5. Kebangsaan : Indonesia m b 6. Tempat tinggal : Kp. Nangoh Rt.002/001 Desa Lemah Duhur Kec. u a Caringin Kab. Bogor 7. Agama : Islam p k 8. Pekerjaan : Tideak Bekerja h a R a i Terdakwa Randy Alias Boy Bin Odih ditahan dalam tahanan rutan oleh: s M 1. Penyidik sejak tanggal 17 Januari 2019 sampai dengan tanggal 5 Februari g e 2019 n n 2. Penyidik Perpanjangan Oleh Penuntut Umum sejak tanggal 6 Februari 2019 o u sampai dengan tanggal 17 Maret 2019 3. Pgenuntut Umum sejak tanggal 18 Maret 2019 sampai dengan tanggdal 6 April 2019 n A 4. Hakim Pengadilan Negeri sejak tanggal 26 Maret 2019 sampai dengan I tanggal 24 April 2019 h k 5. Hakim Pengadilan Negeri Perpanjangan Pertama Oleh Ketua Pengadilan a i Negeri sejak tanggal 25 April 2019 sampai dengan tanggal 23 Juni 2019 l m b Terdakwa menghadap sendiri; u a Pengadilan Negeri tersebut; p k Setelah membaca: e h a - Penetapan Ketua Pengadilan Negeri Cibinong Nomor R a 166/Pid.B/2019/PN Cbi tanggal 26 Maret 2019 tentang penunjukan Majelis i s M Hakim; g e - Penetapan Majelis Hakim Nomor 166/Pid.B/2019/PN Cbi tanggal 26 n Maret 2019 tenntang penetapan hari sidang; - Berkas perkara dan surat-surat lain yang bersangkutan; o u   dari 17 Putusan Nomor 166/Pid.B/2019/PN Cbi d g Form-01/SOP/15.5/2019/PN Cbi n A I h k
Pasal : -
Amar Putusan :
mengadili perkara pidana doengan u acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai d g berikut dalam perkara Terdakwa : n A1. Nama lengkap : Randy Alias Boy Bin Odih 2. Tempat lahir : Bogor I h3. Umur/Tanggal lahir : 32/26 Oktober 1986 k a 4. Jenis kelamin : Laki-laki i l 5. Kebangsaan : Indonesia m b 6. Tempat tinggal : Kp. Nangoh Rt.002/001 Desa Lemah Duhur Kec. u a Caringin Kab. Bogor 7. Agama : Islam p k 8. Pekerjaan : Tideak Bekerja h a R a i Terdakwa Randy Alias Boy Bin Odih ditahan dalam tahanan rutan oleh: s M 1. Penyidik sejak tanggal 17 Januari 2019 sampai dengan tanggal 5 Februari g e 2019 n n 2. Penyidik Perpanjangan Oleh Penuntut Umum sejak tanggal 6 Februari 2019 o u sampai dengan tanggal 17 Maret 2019 3. Pgenuntut Umum sejak tanggal 18 Maret 2019 sampai dengan tanggdal 6 April 2019 n A 4. Hakim Pengadilan Negeri sejak tanggal 26 Maret 2019 sampai dengan I tanggal 24 April 2019 h k 5. Hakim Pengadilan Negeri Perpanjangan Pertama Oleh Ketua Pengadilan a i Negeri sejak tanggal 25 April 2019 sampai dengan tanggal 23 Juni 2019 l m b Terdakwa menghadap sendiri; u a Pengadilan Negeri tersebut; p k Setelah membaca: e h a - Penetapan Ketua Pengadilan Negeri Cibinong Nomor R a 166/Pid.B/2019/PN Cbi tanggal 26 Maret 2019 tentang penunjukan Majelis i s M Hakim; g e - Penetapan Majelis Hakim Nomor 166/Pid.B/2019/PN Cbi tanggal 26 n Maret 2019 tenntang penetapan hari sidang; - Berkas perkara dan surat-surat lain yang bersangkutan; o u   dari 17 Putusan Nomor 166/Pid.B/2019/PN Cbi d g Form-01/SOP/15.5/2019/PN Cbi n A I h k

In [7]:
reuse = pd.DataFrame({

    "query_case":[best_case["case_id"]],

    "nomor_putusan":[solution.iloc[0]["nomor_putusan"]],

    "nama_terdakwa":[solution.iloc[0]["nama_terdakwa"]],

    "pasal":[solution.iloc[0]["pasal"]],

    "amar_putusan":[solution.iloc[0]["amar_putusan"]],

    "similarity":[best_case["similarity"]]

})

reuse

,query_case,nomor_putusan,nama_terdakwa,pasal,amar_putusan,similarity
0,case_001,166/Pid.B/2019/PN,Randy Alias Boy Bin Odih 2. Tempat lahir : Bog...,-,mengadili perkara pidana doengan u acara pemer...,0.955703

In [8]:
SAVE_DIR = os.path.join(
    PROJECT_DIR,
    "data",
    "results"
)

os.makedirs(SAVE_DIR, exist_ok=True)

reuse.to_csv(
    os.path.join(
        SAVE_DIR,
        "reuse_solution.csv"
    ),
    index=False,
    encoding="utf-8-sig"
)

print("Reuse Solution berhasil disimpan.")

Reuse Solution berhasil disimpan.

In [9]:
reuse

,query_case,nomor_putusan,nama_terdakwa,pasal,amar_putusan,similarity
0,case_001,166/Pid.B/2019/PN,Randy Alias Boy Bin Odih 2. Tempat lahir : Bog...,-,mengadili perkara pidana doengan u acara pemer...,0.955703