In [2]:
import os
import pandas as pd
import numpy as np

In [3]:
PROJECT_DIR = os.path.abspath("..")

RESULT_PATH = os.path.join(
    PROJECT_DIR,
    "data",
    "results",
    "retrieval_results.csv"
)

retrieval = pd.read_csv(RESULT_PATH)

retrieval

,case_id,nomor_putusan,nama_terdakwa,pasal,amar_putusan,similarity
0,case_001,166/Pid.B/2019/PN,Randy Alias Boy Bin Odih 2. Tempat lahir : Bog...,-,mengadili perkara pidana doengan u acara pemer...,0.955703
1,case_007,241/Pid.B/2019/PN,Nano Bin Patma; I Tempat lahir : Bogor; h k Um...,-,mengadili perkara pidana doengan u acara pemer...,0.554023
2,case_030,99/Pid.B/2019/PN,ISAK Bin IDING n A Tempat lahir : Sukabumi I U...,pasal 480 KRe,mengadili perkara pidana dengan o u acara peme...,0.214651
3,case_002,182/Pid.B/2021/PN,Odih Al. Belong Bin Rohaca h k 2. Tempat lahir...,-,mengadili perkara pidana dengan d agcara pemer...,0.201285
4,case_003,182/Pid.B/2021/PN,Odih Al. Belong Bin Rohaca h k 2. Tempat lahir...,-,mengadili perkara pidana dengan d agcara pemer...,0.201285

In [4]:
threshold = 0.50

retrieval["prediction"] = np.where(
    retrieval["similarity"] >= threshold,
    "Relevant",
    "Not Relevant"
)

retrieval

,case_id,nomor_putusan,nama_terdakwa,pasal,amar_putusan,similarity,prediction
0,case_001,166/Pid.B/2019/PN,Randy Alias Boy Bin Odih 2. Tempat lahir : Bog...,-,mengadili perkara pidana doengan u acara pemer...,0.955703,Relevant
1,case_007,241/Pid.B/2019/PN,Nano Bin Patma; I Tempat lahir : Bogor; h k Um...,-,mengadili perkara pidana doengan u acara pemer...,0.554023,Relevant
2,case_030,99/Pid.B/2019/PN,ISAK Bin IDING n A Tempat lahir : Sukabumi I U...,pasal 480 KRe,mengadili perkara pidana dengan o u acara peme...,0.214651,Not Relevant
3,case_002,182/Pid.B/2021/PN,Odih Al. Belong Bin Rohaca h k 2. Tempat lahir...,-,mengadili perkara pidana dengan d agcara pemer...,0.201285,Not Relevant
4,case_003,182/Pid.B/2021/PN,Odih Al. Belong Bin Rohaca h k 2. Tempat lahir...,-,mengadili perkara pidana dengan d agcara pemer...,0.201285,Not Relevant

In [5]:
total_case = len(retrieval)

relevant = (retrieval["prediction"] == "Relevant").sum()

not_relevant = (retrieval["prediction"] == "Not Relevant").sum()

print("="*50)
print("HASIL EVALUASI")
print("="*50)
print(f"Jumlah Retrieval : {total_case}")
print(f"Relevant         : {relevant}")
print(f"Not Relevant     : {not_relevant}")

==================================================
HASIL EVALUASI
==================================================
Jumlah Retrieval : 5
Relevant         : 2
Not Relevant     : 3

In [6]:
print("="*50)

print(f"Similarity Max  : {retrieval['similarity'].max():.4f}")
print(f"Similarity Min  : {retrieval['similarity'].min():.4f}")
print(f"Similarity Mean : {retrieval['similarity'].mean():.4f}")
print(f"Similarity Std  : {retrieval['similarity'].std():.4f}")

==================================================
Similarity Max  : 0.9557
Similarity Min  : 0.2013
Similarity Mean : 0.4254
Similarity Std  : 0.3327

In [ ]:
EVAL_DIR = os.path.join(
    PROJECT_DIR,
    "data",
    "eval"
)

os.makedirs(EVAL_DIR, exist_ok=True)

retrieval.to_csv(
    os.path.join(
        EVAL_DIR,
        "evaluation_results.csv"
    ),
    index=False,
    encoding="utf-8-sig"
)

print("Evaluation berhasil disimpan.")

Evaluation berhasil disimpan.

In [8]:
summary = pd.DataFrame({

    "Jumlah Retrieval":[total_case],

    "Relevant":[relevant],

    "Not Relevant":[not_relevant],

    "Similarity Max":[retrieval["similarity"].max()],

    "Similarity Mean":[retrieval["similarity"].mean()]

})

summary

   Jumlah Retrieval  Relevant  Not Relevant  Similarity Max  Similarity Mean
0                 5         2             3        0.955703         0.425389

In [9]:
summary.to_csv(

    os.path.join(
        EVAL_DIR,
        "evaluation_summary.csv"
    ),

    index=False,

    encoding="utf-8-sig"

)

print("Summary berhasil disimpan.")

Summary berhasil disimpan.